/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ni.edu.uni.programacion.views.panels;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Denzell Connolly
 */
public class PnlCurrency extends javax.swing.JPanel {

    public JButton getBtnConv() {
        return btnConv;
    }

    public void setBtnConv(JButton btnConv) {
        this.btnConv = btnConv;
    }

    public JButton getBtnCs() {
        return btnCs;
    }

    public void setBtnCs(JButton btnCs) {
        this.btnCs = btnCs;
    }

    public JButton getBtnNew() {
        return btnNew;
    }

    public void setBtnNew(JButton btnNew) {
        this.btnNew = btnNew;
    }

    public JButton getBtnSc() {
        return btnSc;
    }

    public void setBtnSc(JButton btnSc) {
        this.btnSc = btnSc;
    }

    public JLabel getLblMoneda1() {
        return lblMoneda1;
    }

    public void setLblMoneda1(JLabel lblMoneda1) {
        this.lblMoneda1 = lblMoneda1;
    }

    public JLabel getLblMoneda2() {
        return lblMoneda2;
    }

    public void setLblMoneda2(JLabel lblMoneda2) {
        this.lblMoneda2 = lblMoneda2;
    }

    public JTextField getTxtMoneda1() {
        return txtMoneda1;
    }

    public void setTxtMoneda1(JTextField txtMoneda1) {
        this.txtMoneda1 = txtMoneda1;
    }

    public JTextField getTxtMoneda2() {
        return txtMoneda2;
    }

    public void setTxtMoneda2(JTextField txtMoneda2) {
        this.txtMoneda2 = txtMoneda2;
    }

    
    
    /**
     * Creates new form PnlCurrency
     */
    public PnlCurrency() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        btnConv = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnCs = new javax.swing.JButton();
        btnSc = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblMoneda1 = new javax.swing.JLabel();
        txtMoneda1 = new javax.swing.JTextField();
        lblMoneda2 = new javax.swing.JLabel();
        txtMoneda2 = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        btnConv.setText("Convertir");
        jPanel1.add(btnConv);

        btnNew.setText("Nuevo");
        jPanel1.add(btnNew);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);

        btnCs.setText("C$ - $");
        jPanel2.add(btnCs);

        btnSc.setText("$ - C$");
        jPanel2.add(btnSc);

        add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(new java.awt.GridBagLayout());

        lblMoneda1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMoneda1.setText("C$");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel3.add(lblMoneda1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel3.add(txtMoneda1, gridBagConstraints);

        lblMoneda2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMoneda2.setText("$");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel3.add(lblMoneda2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel3.add(txtMoneda2, gridBagConstraints);

        add(jPanel3, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConv;
    private javax.swing.JButton btnCs;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSc;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblMoneda1;
    private javax.swing.JLabel lblMoneda2;
    private javax.swing.JTextField txtMoneda1;
    private javax.swing.JTextField txtMoneda2;
    // End of variables declaration//GEN-END:variables
}
