/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ni.edu.uni.programacion.views.panels;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Denzell Connolly
 */
public class PnlTemp extends javax.swing.JPanel {

    public JLabel getLblTemp1() {
        return lblTemp1;
    }

    public void setLblTemp1(JLabel lblTemp1) {
        this.lblTemp1 = lblTemp1;
    }

    public JLabel getLblTemp2() {
        return lblTemp2;
    }

    public void setLblTemp2(JLabel lblTemp2) {
        this.lblTemp2 = lblTemp2;
    }

    
    
    public JButton getBntFc() {
        return bntFc;
    }

    public void setBntFc(JButton bntFc) {
        this.bntFc = bntFc;
    }

    public JButton getBtnCf() {
        return btnCf;
    }

    public void setBtnCf(JButton btnCf) {
        this.btnCf = btnCf;
    }

    
    
    public JButton getBtnConv() {
        return btnConv;
    }

    public void setBtnConv(JButton btnConv) {
        this.btnConv = btnConv;
    }

    public JButton getBtnNew() {
        return btnNew;
    }

    public void setBntNew(JButton btnNew) {
        this.btnNew = btnNew;
    }

    public JTextField getTxtTemp1() {
        return txtTemp1;
    }

    public void setTxtTemp1(JTextField txtTemp1) {
        this.txtTemp1 = txtTemp1;
    }

    public JTextField getTxtTemp2() {
        return txtTemp2;
    }

    public void setTxtTemp2(JTextField txtTemp2) {
        this.txtTemp2 = txtTemp2;
    }

    
    
    
    /**
     * Creates new form PnlTemp
     */
    public PnlTemp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        btnConv = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblTemp1 = new javax.swing.JLabel();
        txtTemp1 = new javax.swing.JTextField();
        lblTemp2 = new javax.swing.JLabel();
        txtTemp2 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        bntFc = new javax.swing.JButton();
        btnCf = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.FlowLayout(2));

        btnConv.setText("Convertir");
        jPanel1.add(btnConv);

        btnNew.setText("Nuevo");
        jPanel1.add(btnNew);

        add(jPanel1, java.awt.BorderLayout.SOUTH);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        lblTemp1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTemp1.setText("F");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel2.add(lblTemp1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel2.add(txtTemp1, gridBagConstraints);

        lblTemp2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTemp2.setText("C");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel2.add(lblTemp2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel2.add(txtTemp2, gridBagConstraints);

        add(jPanel2, java.awt.BorderLayout.CENTER);

        bntFc.setText("F - C");
        jPanel3.add(bntFc);

        btnCf.setText("C - F");
        jPanel3.add(btnCf);

        add(jPanel3, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntFc;
    private javax.swing.JButton btnCf;
    private javax.swing.JButton btnConv;
    private javax.swing.JButton btnNew;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblTemp1;
    private javax.swing.JLabel lblTemp2;
    private javax.swing.JTextField txtTemp1;
    private javax.swing.JTextField txtTemp2;
    // End of variables declaration//GEN-END:variables
}
